In [1]:
print("E-commerce Intelligence Project")
print("Python environment is working!")

E-commerce Intelligence Project
Python environment is working!

In [2]:
import pandas as pd

In [3]:
from pathlib import Path

DATA_PATH = Path("../01_Raw_Data/archive (1)")

In [4]:
list(DATA_PATH.glob("*.csv"))

[WindowsPath('../01_Raw_Data/archive (1)/olist_customers_dataset.csv'),
 WindowsPath('../01_Raw_Data/archive (1)/olist_geolocation_dataset.csv'),
 WindowsPath('../01_Raw_Data/archive (1)/olist_orders_dataset.csv'),
 WindowsPath('../01_Raw_Data/archive (1)/olist_order_items_dataset.csv'),
 WindowsPath('../01_Raw_Data/archive (1)/olist_order_payments_dataset.csv'),
 WindowsPath('../01_Raw_Data/archive (1)/olist_order_reviews_dataset.csv'),
 WindowsPath('../01_Raw_Data/archive (1)/olist_products_dataset.csv'),
 WindowsPath('../01_Raw_Data/archive (1)/olist_sellers_dataset.csv'),
 WindowsPath('../01_Raw_Data/archive (1)/product_category_name_translation.csv')]

In [5]:
orders = pd.read_csv(
    DATA_PATH / "olist_orders_dataset.csv"
)

In [6]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [7]:
orders.shape

(99441, 8)

In [8]:
orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='str')

In [9]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

In [10]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [1]:
orders_clean.dtypes

NameError: name 'orders_clean' is not defined

In [2]:
import pandas as pd

In [4]:
from pathlib import Path

DATA_PATH = Path("../01_Raw_Data/archive (1)")

In [5]:
orders = pd.read_csv(
    DATA_PATH / "olist_orders_dataset.csv"
)

In [6]:
orders_clean = orders.copy()

In [7]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for column in date_columns:
    orders_clean[column] = pd.to_datetime(
        orders_clean[column],
        errors="coerce"
    )

In [8]:
orders_clean.dtypes

order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

In [10]:
delivered_orders = orders_clean[
    orders_clean["order_status"] == "delivered"
].copy()

In [11]:
delivered_orders["delivery_days"] = (
    delivered_orders["order_delivered_customer_date"]
    - delivered_orders["order_purchase_timestamp"]
).dt.total_seconds() / (24 * 60 * 60)

In [12]:
delivery_days = 3

In [13]:
delivery_days

3

In [14]:
delivered_orders["delivery_days"].head()

0     8.436574
1    13.782037
2     9.394213
3    13.208750
4     2.873877
Name: delivery_days, dtype: float64

In [15]:
delivered_orders["delivery_days"].mean()

np.float64(12.558217098051975)

In [16]:
average_delivery_days = delivered_orders["delivery_days"].mean()

round(average_delivery_days, 2)

np.float64(12.56)

In [19]:
delivered_orders["is_on_time"] = (
    delivered_orders["order_delivered_customer_date"]
    <= delivered_orders["order_estimated_delivery_date"]
)

In [20]:
on_time_rate = delivered_orders["is_on_time"].mean() * 100

round(on_time_rate, 2)

np.float64(91.88)

In [21]:
late_rate = 100 - on_time_rate

round(late_rate, 2)

np.float64(8.12)

In [22]:
delivered_orders["days_late"] = (
    delivered_orders["order_delivered_customer_date"]
    - delivered_orders["order_estimated_delivery_date"]
).dt.total_seconds() / (24 * 60 * 60)

In [23]:
average_days_late = late_orders["days_late"].mean()

round(average_days_late, 2)

NameError: name 'late_orders' is not defined

In [24]:
late_orders = delivered_orders[
    delivered_orders["days_late"] > 0
].copy()

In [25]:
average_days_late = late_orders["days_late"].mean()

round(average_days_late, 2)

np.float64(9.55)

In [26]:
customers = pd.read_csv(
    DATA_PATH / "olist_customers_dataset.csv"
)

In [27]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [28]:
orders_with_customers = delivered_orders.merge(
    customers[
        [
            "customer_id",
            "customer_city",
            "customer_state"
        ]
    ],
    on="customer_id",
    how="left"
)

In [29]:
orders_with_customers[
    [
        "order_id",
        "customer_id",
        "customer_city",
        "customer_state",
        "delivery_days",
        "is_on_time"
    ]
].head()

,order_id,customer_id,customer_city,customer_state,delivery_days,is_on_time
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,sao paulo,SP,8.436574,True
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,barreiras,BA,13.782037,True
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,vianopolis,GO,9.394213,True
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,sao goncalo do amarante,RN,13.208750,True
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,santo andre,SP,2.873877,True

In [30]:
state_delivery = (
    orders_with_customers
    .groupby("customer_state")
    .agg(
        total_orders=("order_id", "count"),
        on_time_rate=("is_on_time", "mean"),
        avg_delivery_days=("delivery_days", "mean")
    )
    .reset_index()
)

state_delivery["on_time_rate"] = (
    state_delivery["on_time_rate"] * 100
)

state_delivery["on_time_rate"] = (
    state_delivery["on_time_rate"].round(2)
)

state_delivery["avg_delivery_days"] = (
    state_delivery["avg_delivery_days"].round(2)
)

In [31]:
state_delivery.sort_values(
    "on_time_rate"
).head(10)

   customer_state  total_orders  on_time_rate  avg_delivery_days
1              AL           397         76.07              24.54
9              MA           717         80.33              21.57
16             PI           476         84.03              19.46
5              CE          1279         84.68              21.27
24             SE           335         84.78              21.52
4              BA          3256         85.96              19.34
18             RJ         12350         86.53              15.31
26             TO           274         87.23              17.66
13             PA           946         87.63              23.77
7              ES          1995         87.77              15.79